//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISeCommerce.AdminWebsite {
    
    
    public partial class FullWidthUnsecured {
        
        /// <summary>
        /// divFullColumn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divFullColumn;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ISeCommerce.AdminWebsite.MasterPages.Main Master {
            get {
                return ((ISeCommerce.AdminWebsite.MasterPages.Main)(base.Master));
            }
        }
    }
}
